name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
      - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    paths:
      - book/**

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Clone submodules
        run: |
          git submodule update --init --recursive

      - name: Update pip
        run: |
          python -m pip install -U pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Install development dependencies
        run: |
          python -m pip install -r requirements-dev.txt

      # Build the book
      - name: Build the book
        run: |
          make html

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
